<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ips_bringup</name>
  <version>0.2.0</version>
  <description>Launch + config bringup package for the IPS system.</description>
  <maintainer email="karei@todo.local">Karei</maintainer>
  <license>MIT</license>

  <exec_depend>ips_msgs</exec_depend>
  <exec_depend>ips_nodes</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
